apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-masters
  namespace: system
spec:  
  version: 8.6.0  
  nodeSets:
  - name: master-b
    count: 1
    config:
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "master" ]              
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c8-r16       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 16Gi
              cpu: '8'
            limits:
              memory: 16Gi
              cpu: '8' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: master-c
    count: 1
    config:
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "master" ]              
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c8-r16
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 16Gi
              cpu: '8'
            limits:
              memory: 16Gi
              cpu: '8' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']          
  - name: hot-b
    count: 1
    config:
      node.attr.data: hot      
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_hot", "data_content" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r8       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '4'
            limits:
              memory: 8Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']    
  - name: hot-c
    count: 1
    config:
      node.attr.data: hot      
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_hot", "data_content" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r8       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '4'
            limits:
              memory: 8Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']                     
  - name: warm-b
    count: 1
    config:
      node.attr.data: warm      
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_warm" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: warm                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r4       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: '4'
            limits:
              memory: 4Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']         
  - name: warm-c
    count: 1
    config:
      node.attr.data: warm      
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_warm" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: warm                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r4       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: '4'
            limits:
              memory: 4Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']                  
  - name: cold-b
    count: 1
    config:
      node.attr.data: cold      
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_cold" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: cold                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r4       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: '4'
            limits:
              memory: 4Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']        
  - name: cold-c
    count: 1
    config:
      node.attr.data: cold      
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_cold" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: cold                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r4       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: '4'
            limits:
              memory: 4Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']                  
  - name: ingest-b
    count: 1
    config:
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "ingest" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r8       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '4'
            limits:
              memory: 8Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: ingest-c
    count: 1
    config:
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "ingest" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r8       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '4'
            limits:
              memory: 8Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']          
  - name: coordinate-b
    count: 1
    config:
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: []
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r8       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '4'
            limits:
              memory: 8Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: coordinate-c
    count: 1
    config:
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: []
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c4-r8       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '4'
            limits:
              memory: 8Gi
              cpu: '4' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']          
  - name: transform-b
    count: 1
    config:
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "transform" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c8-r16       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 16Gi
              cpu: '8'
            limits:
              memory: 16Gi
              cpu: '8' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']         
  - name: transform-c
    count: 1
    config:
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "transform" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: n-c8-r16       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 16Gi
              cpu: '8'
            limits:
              memory: 16Gi
              cpu: '8' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']                              
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: system
spec:
  version: 8.6.0
  count: 1
  elasticsearchRef:
    name: elastic-masters
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://elastic-masters-es-http.system.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.system.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        namespace: system
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: system
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
  podTemplate:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: n-c8-r16       
      containers:
      - name: kibana
        resources:
          requests:
            memory: 16Gi
            cpu: '8'
          limits:
            memory: 16Gi
            cpu: '8' 
      initContainers:
      - name: sysctl
        securityContext:
          privileged: true
          runAsUser: 0
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']            
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: system  
spec:
  version: 8.6.0
  kibanaRef:
    name: kibana
  elasticsearchRefs:
  - name: elastic-masters
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: elastic-agent
  namespace: system  
spec:
  version: 8.6.0
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: agent
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 0.1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server
subjects:
- kind: ServiceAccount
  name: fleet-server
  namespace: system
roleRef:
  kind: ClusterRole
  name: fleet-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  - events
  - services
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
- apiGroups: ["extensions"]
  resources:
    - replicasets
  verbs: 
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: system
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kb
spec:
  scaleTargetRef:
    apiVersion: kibana.k8s.elastic.co/v1
    kind: Kibana
    name: kibana
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  
