apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hs-elastic
  namespace: elasticsearch
spec:
  version: 8.16.0
  nodeSets:
    # Master Nodes
    - name: master
      count: 3
      config:
        node.roles: ["master"]
        cluster.routing.allocation.awareness.attributes: zone
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: master-pool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4Gi
                  cpu: "2"
                limits:
                  memory: 4Gi
                  cpu: "2"

    # Data Nodes
    - name: data
      count: 3
      config:
        node.roles: ["data"]
        cluster.routing.allocation.awareness.attributes: zone
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5120Gi
            storageClassName: standard
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: data-pool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 16Gi
                  cpu: "4"
                limits:
                  memory: 16Gi
                  cpu: "4"

    # Ingest Nodes
    - name: ingest
      count: 2
      config:
        node.roles: ["ingest"]
        cluster.routing.allocation.awareness.attributes: zone
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: ingest-pool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: "2"
                limits:
                  memory: 8Gi
                  cpu: "2"

    # Coordinate Nodes
    - name: coordinate
      count: 2
      config:
        node.roles: []
        cluster.routing.allocation.awareness.attributes: zone
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: coordinate-pool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4Gi
                  cpu: "2"
                limits:
                  memory: 4Gi
                  cpu: "2"

    # Transform Nodes
    - name: transform
      count: 2
      config:
        node.roles: ["transform"]
        cluster.routing.allocation.awareness.attributes: zone
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: transform-pool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4Gi
                  cpu: "2"
                limits:
                  memory: 4Gi
                  cpu: "2"
