apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elasticsearch
spec:
  version: 8.16.0
  kibanaRef:
    name: kibana
    namespace: elasticsearch
  elasticsearchRefs:
    - name: hs-elastic
      namespace: elasticsearch
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 2
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: fleet-kibana-pool
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        containers:
          - name: agent
            resources:
              requests:
                memory: 4Gi
                cpu: "2"
              limits:
                memory: 4Gi
                cpu: "2"
