apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: elasticsearch
spec:
  version: 8.16.0
  fleetServerRef:
    name: fleet-server
    namespace: elasticsearch
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
          - operator: Exists
            effect: NoExecute
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        containers:
          - name: agent
            resources:
              requests:
                memory: 2Gi
                cpu: "1"
              limits:
                memory: 2Gi
                cpu: "1"
