---
# Namespace for Elastic Stack
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
# Elasticsearch Deployment
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic
spec:
  version: 8.16.1
  nodeSets:
    # Master Nodes
    - name: master-nodes
      count: 3
      config:
        node.roles: ["master"]
        cluster.name: "elastic-cluster"
      podTemplate:
        spec:
          nodeSelector:
            role: master
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

    # Data Nodes
    - name: data-nodes
      count: 6
      config:
        node.roles: ["data"]
        cluster.routing.allocation.awareness.attributes: "zone"
      podTemplate:
        spec:
          nodeSelector:
            role: data
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "64Gi"
                  cpu: "16"
                limits:
                  memory: "64Gi"
                  cpu: "16"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 4Ti

    # Ingest Nodes
    - name: ingest-nodes
      count: 2
      config:
        node.roles: ["ingest"]
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

    # Coordinator Nodes
    - name: coordinator-nodes
      count: 2
      config:
        node.roles: ["coordinating_only"]
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

    # Transform Nodes
    - name: transform-nodes
      count: 2
      config:
        node.roles: ["transform"]
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

---
# Kibana Deployment
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elastic-cluster
  podTemplate:
    spec:
      nodeSelector:
        role: shared
      containers:
        - name: kibana
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "2"

---
# Fleet Server Deployment
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic
spec:
  version: 8.16.1
  elasticsearchRefs:
    - name: elastic-cluster
  deployment:
    replicas: 2
    podTemplate:
      spec:
        nodeSelector:
          role: shared
        containers:
          - name: fleet-server
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "4Gi"
                cpu: "2"

---
# Elastic Agent Deployment
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: elastic
spec:
  version: 8.16.1
  elasticsearchRefs:
    - name: elastic-cluster
  daemonSet:
    podTemplate:
      spec:
        nodeSelector:
          role: shared
        containers:
          - name: elastic-agent
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "4Gi"
                cpu: "2"
