---
# Elasticsearch Deployment
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic
spec:
  version: 8.16.1
  nodeSets:
    # Master Nodes
    - name: master-nodes
      count: 3
      config:
        node.roles: ["master"]
        cluster.name: "elastic-cluster"
      podTemplate:
        spec:
          nodeSelector:
            role: master
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "2Gi"  # Adjusted to 2Gi memory per master node
                  cpu: "1"       # Adjusted to 1 CPU per master node
                limits:
                  memory: "2Gi"
                  cpu: "1"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

    # Data Nodes
    - name: data-nodes
      count: 6
      config:
        node.roles: ["data"]
        cluster.routing.allocation.awareness.attributes: "zone"
      podTemplate:
        spec:
          nodeSelector:
            role: data
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "16Gi"  # Adjusted to 16Gi memory per data node
                  cpu: "4"        # Adjusted to 4 CPUs per data node
                limits:
                  memory: "32Gi"  # Limit adjusted to 32Gi memory
                  cpu: "8"        # Limit adjusted to 8 CPUs per data node
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 4Ti

    # Ingest Nodes
    - name: ingest-nodes
      count: 2
      config:
        node.roles: ["ingest"]
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "2Gi"  # Adjusted to 2Gi memory per ingest node
                  cpu: "1"        # Adjusted to 1 CPU per ingest node
                limits:
                  memory: "2Gi"
                  cpu: "1"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

    # Coordinator Nodes
    - name: coordinator-nodes
      count: 2
      config:
        node.roles: ["coordinating_only"]
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "2Gi"  # Adjusted to 2Gi memory per coordinator node
                  cpu: "1"        # Adjusted to 1 CPU per coordinator node
                limits:
                  memory: "2Gi"
                  cpu: "1"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

    # Transform Nodes
    - name: transform-nodes
      count: 2
      config:
        node.roles: ["transform"]
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "2Gi"  # Adjusted to 2Gi memory per transform node
                  cpu: "1"        # Adjusted to 1 CPU per transform node
                limits:
                  memory: "2Gi"
                  cpu: "1"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: ssd-storage
            resources:
              requests:
                storage: 50Gi

---
# Fleet Server Deployment
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic
spec:
  version: 8.16.1
  elasticsearchRefs:
    - name: elastic-cluster
  deployment:
    replicas: 2
    podTemplate:
      spec:
        containers:
          - name: fleet-server
            image: "docker.elastic.co/beats/elastic-agent:8.16.1"  # Add Fleet Server image
            resources:
              requests:
                memory: "2Gi"  # Adjusted to 2Gi memory for fleet server
                cpu: "1"        # Adjusted to 1 CPU for fleet server
              limits:
                memory: "2Gi"
                cpu: "1"

---
# Elastic Agent Deployment
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: elastic
spec:
  version: 8.16.1
  elasticsearchRefs:
    - name: elastic-cluster
  daemonSet:
    podTemplate:
      spec:
        containers:
          - name: elastic-agent
            image: "docker.elastic.co/beats/elastic-agent:8.16.1"  # Add Elastic Agent image
            resources:
              requests:
                memory: "2Gi"  # Adjusted to 2Gi memory for agent
                cpu: "1"        # Adjusted to 1 CPU for agent
              limits:
                memory: "2Gi"
                cpu: "1"
