---
# Elasticsearch Deployment
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic
spec:
  version: 8.16.1
  nodeSets:
    # Master Nodes (3 for HA)
    - name: master-nodes
      count: 3
      config:
        node.roles: ["master"]
        cluster.name: "elastic-cluster"
        cluster.routing.allocation.awareness.attributes: "zone"  # Zone awareness
      podTemplate:
        spec:
          nodeSelector:
            role: master
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 50Gi

    # Data Nodes (2 nodes across 2 zones, 1 node per zone, 24TB per node)
    - name: data-nodes
      count: 2
      config:
        node.roles: ["data"]
        cluster.routing.allocation.awareness.attributes: "zone"  # Zone awareness for data nodes
      podTemplate:
        spec:
          nodeSelector:
            role: data
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "32Gi"  # Adjusted to 16Gi memory per data node
                  cpu: "8"        # Adjusted to 4 CPUs per data node
                limits:
                  memory: "32Gi"  # Limit adjusted to 32Gi memory
                  cpu: "8"        # Limit adjusted to 8 CPUs per data node
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 24Ti  # Each data node gets 24Ti storage

    # Ingest Nodes (2 for HA)
    - name: ingest-nodes
      count: 2
      config:
        node.roles: ["ingest"]
        cluster.routing.allocation.awareness.attributes: "zone"
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 50Gi

    # Coordinator Nodes (2 for HA)
    - name: coordinator-nodes
      count: 2
      config:
        node.roles: ["coordinating_only"]
        cluster.routing.allocation.awareness.attributes: "zone"
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 50Gi

    # Transform Nodes (2 for HA)
    - name: transform-nodes
      count: 2
      config:
        node.roles: ["transform"]
        cluster.routing.allocation.awareness.attributes: "zone"
      podTemplate:
        spec:
          nodeSelector:
            role: shared
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "4Gi"
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 50Gi

---
# Fleet Server Deployment (2 replicas for HA)
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic
spec:
  version: 8.16.1
  elasticsearchRefs:
    - name: elastic-cluster
  deployment:
    replicas: 2   # 2 replicas for HA setup
    podTemplate:
      spec:
        containers:
          - name: fleet-server
            image: "docker.elastic.co/beats/elastic-agent:8.16.1"  # Fleet Server image
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "4Gi"
                cpu: "2"

---
# Elastic Agent Deployment (2 replicas for HA)
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: elastic
spec:
  version: 8.16.1
  elasticsearchRefs:
    - name: elastic-cluster
  deployment:
    replicas: 2   # 2 replicas for HA setup
    podTemplate:
      spec:
        containers:
          - name: elastic-agent
            image: "docker.elastic.co/beats/elastic-agent:8.16.1"  # Elastic Agent image
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "4Gi"
                cpu: "2"
