apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-hot
  namespace: system
spec:  
  version: 8.5.3
  elasticsearchRefs:
  - name: elastic-masters
  nodeSets:
  - name: hot-b
    count: 1
    config:
      node.attr.data: hot      
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_hot", "data_content" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: masters       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '3'
            limits:
              memory: 8Gi
              cpu: '3' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']          
  - name: hot-c
    count: 1
    config:
      node.attr.data: hot      
      node.attr.zone: europe-west1-c
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_hot", "data_content" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: masters       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '3'
            limits:
              memory: 8Gi
              cpu: '3' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']    
  - name: hot-d
    count: 1
    config:
      node.attr.data: hot      
      node.attr.zone: europe-west1-d
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "data_hot", "data_content" ]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hot                    
    podTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-nodepool: masters       
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: '3'
            limits:
              memory: 8Gi
              cpu: '3' 
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
                  
