apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.5.3
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        selector:
          matchLabels:
            type: master
        containers:
        - name: elasticsearch        
          resources:
            requests:
              memory: 4Gi
              cpu: 8
            limits:
              memory: 4Gi
