apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: system
spec:
  containers:
  - name: zone-b
    version: 8.5.3  
    config:
      node.attr.zone: europe-west1-b
      cluster.routing.allocation.awareness.attributes: zone
      node.roles: [ "master" ]  
    resources:
      requests:
        storage: 100Gi
        memory: 16Gi
        cpu: 8
      limits:
        memory: 16Gi
        cpu: 8       
    volumeClaimDeletePolicy: DeleteOnScaledownOnly  
    specs:
      nodeSelector: 
        type: master
  initContainers:
    - name: sysctl
    securityContext:
      privileged: true
      runAsUser: 0
      command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
