apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart   
  version: 8.5.3
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:     
        containers:
        - name: elasticsearch

          resources:
            requests:
              memory: 4Gi
              cpu: 8
            limits:
              memory: 4Gi
        nodeName: masters
